#cloud-config
packages:
  - vim
  - mawk
  - sed
write_files:
  - content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            dhcp4: no
            addresses: [10.13.3.__IP_ADDRESS__/24]
            gateway4: 10.13.3.1
            nameservers:
              addresses: [10.13.3.2]
    owner: "root:root"
    path: /root/99-z.yaml
    permissions: '0644'
  - content: |
      #!/bin/bash -ex
      if [[ "$(hostname)" == "s4lp"* ]]; then
          echo "not a container, do nothing"
          exit 0
      fi
      IP_ADDRESS=$(hostname | awk -F'-' '{print 1$3$5}')
      sed "s/__IP_ADDRESS__/${IP_ADDRESS}/g" /root/99-z.yaml > /etc/netplan/99-z.yaml
      netplan apply
      apt-get -qqq update
    owner: "root:root"
    path: /root/gen-net.sh
    permissions: '0777'
preruncmd:
  - "/root/gen-net.sh || echo not found"
